### ISSUE TITLE
LargestEmptyCircle crash on malformed input

### ISSUE THREAD

**Issue by pramsey** [libgeos/geos#1003]
From https://trac.osgeo.org/postgis/ticket/5626#comment:3

Test case for LargestEmptyCircleTest.cpp

```
// https://trac.osgeo.org/postgis/ticket/5626
template<>
template<>
void object::test<20>()
{
    checkCircle(
        "POINT(-11 40)", // input
        "POLYGON((-71.1 42.3,-71.1 42.4,-71.2 42.3,-71.1 42.3))", // boundary
        1, // build tolerance
        5.5, 4.5, 2.12 ); // expected x, y, radius
}
```
This doesn't appear to be structural, other combinations of point geometry outside of the polygon boundary don't yield a crash. On the other hand, the crash doesn't seem to be a tightly bounded numerical issue, as this rounded up version of the initial bug report still crashes.

**Comment by dr-jts** [comment]
Works in JTS.

**Comment by dr-jts** [comment]
It looks like the issue is the horizontal edge at the bottom of the triangle:  `LINESTRING(-71.2 42.3,-71.1 42.3)`.  Lengthening the edge while keeping it horizontal still crashes.  Moving other vertices around doesn't cause a crash.

**Comment by robe2** [comment]
@pramsey  @dr-jts are you sure this isn't a recent issue.  I saw the error locally when I was fixing the garden tests, but even with my fixes I didn't see berrie and berrie64 (the two raspberry pis we have testing PostGIS and GEOS).  But then I realized I had them testing against 3.12.0 (instead of following the branches).

I'm going to check the GEOS old versions I have lieing around to check, but given JTS can't trigger it, I'm thinking its an issue introduced in a recent micro release.

**Comment by dr-jts** [comment]
> I'm going to check the GEOS old versions I have lieing around to check, but given JTS can't trigger it, I'm thinking its an issue introduced in a recent micro release.

Sounds good, I'll check too.

**Comment by pramsey** [comment]
You are correct, 3.12.0 does not crash.

**Comment by dr-jts** [comment]
It might be due to #939.

**Comment by robe2** [comment]
> You are correct, 3.12.0 does not crash.

I just tested on 3.12.2dev and no crash (so looks like this is a new issue in 3.13 cycle)
