### ISSUE TITLE
Cannot parse EMPTY token with white space

### ISSUE THREAD

**Issue by pramsey** [libgeos/geos#1013]
This does not parse
```
MULTIPOINT( EMPTY, (10 10), (20 20))
```
this does
```
MULTIPOINT(EMPTY, (10 10), (20 20))
```
Here's a test case
```c++
// EMPTY token with some white space
template<>
template<>
void object::test<24>
()
{
    GeomPtr geom(wktreader.read("MULTIPOINT( EMPTY, (10 10), (20 20))"));
    auto ngeoms = geom->getNumGeometries();

    ensure(ngeoms == 3);
}
```

**Comment by JamesParrott** [comment]
Hi Paul,

Thanks for the example.  I could easily reproduce it Python, using shapely.from_wkt

```
>>> shapely.from_wkt("MULTIPOINT( EMPTY, (10 10), (20 20))")
...
shapely.errors.GEOSException: ParseException: Expected number but encountered word: 'EMPTY'
```

Within the Geos code base, it certainly seems like the intention was to ignore whitespace, as `str.find_first_not_of(" \r\n\t",... ` is used  (notice the space in the string `" \r\n\t"`), both in `StringTokenizer::peekNextToken`, https://github.com/libgeos/geos/blob/0aef713ac930e7247c50a1ae720c36f0f0bf790a/src/io/StringTokenizer.cpp#L145. and in `StringTokenizer::nextToken` 

### Possible explanation

Within `WKTReader::readMultiPointText`, https://github.com/libgeos/geos/blob/0aef713ac930e7247c50a1ae720c36f0f0bf790a/src/io/WKTReader.cpp#L331, on encountering EMPTY precedd by a space, either `tokenizer->peekNextToken` does return the enum `StringTokenizer::TT_WORD`, (or perhaps due to some unlikely, very subtle bug it incorrectly returns `StringTokenizer::TT_NUMBER`).  The error handling final else clause has nothing to do with it.  In either scenario, flow continues to call `WKTReader::getPreciseCoordinate` (either directly in the number case), or if treated as TT_WORD) probably via calls to `WKTReader::readPointText` and `WKTReader::getCoordinates`. This calls `WKTReader::getNextNumber`

The Exception seen in Shapely above: ` Expected number but encountered word: 'EMPTY'`, is thrown inside ``WKTReader::getNextNumber``  https://github.com/libgeos/geos/blob/0aef713ac930e7247c50a1ae720c36f0f0bf790a/src/io/WKTReader.cpp#L140

If `StringTokenizer::TT_WORD` ie being returned correctly by `tokenizer->peekNextToken`, then within `WKTReader::getCoordinates` possibly the check for EMPTY at https://github.com/libgeos/geos/blob/0aef713ac930e7247c50a1ae720c36f0f0bf790a/src/io/WKTReader.cpp#L66 is being missed, as perhaps 
in `WKTReader::getNextEmptyOrOpener`, within the call therein to ``WKTReader::getNextWord`, the problem is that
a call to `tokenizer->nextToken()` is made, which advances the iterator, instead of `tokenizer->peekNextToken`?

All those functions are fundamental to the module though, well tested, and used by so many other entry points, that very strong justification is needed before changing them.  There's a big risk of breaking something else in fixing this particular bug


Before I spend longer digging in to this, please could someone confirm what the intended scope of wkt that geos will parse is?  In the Geos  WKT grammar spec, EMPTY is not supported -within the parens- in Multipoints at all (A multipoint is either a non-empty sequence of points, or it's empty.  And a point cannot be empty):

```
<point> ::= <x> <y> [ <z> ] [ <m> ]

<multipoint text> ::=
    <empty set> |
    <left paren> <point> {<comma> <point>} ... <right paren>

<multipoint text representation> ::=
    MULTIPOINT [ <zm> ] <multipoint text>
```
https://libgeos.org/specifications/wkt/

So yes this is a bug.  But please can someone confirm that the the bug is not because EMPTY should not be supported in MULTIPOINT at all?

Parsers can be free to choose to parse a superset of a standard (if that standard doesn't require an error to be raised on invalid grammar).  WKT is intended to be human readable.  Either requiring structural whitespace or forbidding it would both defeat that very purpose.  More importantly, in the official WKT spec, section 7.2.2 (2D geom only), multipoints are defined as empty, or a non-empty sequence of point texts, and point texts may be empty:

```
<multipoint tagged text> ::= multipoint <multipoint text> 
<multipoint text> ::= <empty set> | <left paren><point text>{<comma> <point text>}* <right paren>
<point text> ::= <empty set> | <left paren> <point> <right paren> 
 <point> ::= <x> <y> 

```

https://www.ogc.org/standard/sfa/
https://portal.ogc.org/files/?artifact_id=25355

So perhaps my point is just a quibble that the BNF for WKT in the geos documentation needs making consistent with (the OG) the OGC's.
