### ISSUE TITLE
[FR] optional GPU acceleration using OpenCL or Vulkan Compute

### ISSUE THREAD

**Issue by eadmaster** [libgeos/geos#1038]
this is [supported with GDAL currently](https://stackoverflow.com/questions/64558912/how-do-i-build-gdal-with-opencl-against-a-custom-cuda-installation), would be nice to have on GEOS as well to accelerate derived python libraries like Shapely.

**Comment by pramsey** [comment]
This isn't quite like raster ops, where great gobs of float point ops are a major part of the processing. There are relatively few tight loops, at least over the swatch of CPU time spent. I'm going to close this out, if you have working code, put together a PR. The real win is finding GPU accelerated algorithms for core pieces of computational geometry, like triangulation for example, so that everything depending on triangulation then gets a shot in the arm.
