### ISSUE TITLE
Edge of intersection not matching the edge of original polygon

### ISSUE THREAD

**Issue by martinfleis** [libgeos/geos#1109]
I've encountered a puzzling issue which is probably linked to some floating point precision (though setting a precision grid does not help), when the result of intersection between geometries does not have a boundary matching the expected boundary of the smallest of the intersecting polygons. You can see the original use case in https://github.com/pysal/momepy/pull/598.

Here's a small example derived from the original issue using shapely.

```py
import shapely

geom = shapely.from_wkt(
    "POLYGON ((1603268.502117987 6464060.781328565, 1603296.8217964454 6464047.851641227, 1603349.1085612718 6464035.338499875, 1603363.557831175 6464031.88480676, 1603361.0308787343 6464021.107210826, 1603317.7832565615 6463836.796863219, 1603217.2506244255 6463859.844110653, 1603202.3783404578 6463872.287568242, 1603157.794884393 6463914.581579376, 1603146.6963311615 6463924.630126579, 1603157.0490438067 6463936.205929175, 1603258.3275165292 6464049.413615812, 1603268.502117987 6464060.781328565))"
)
points = shapely.from_wkt(
    [
        "POINT (1603284.828798125 6464019.5353853395)",
        "POINT (1603323.0633351507 6464000.228348275)",
        "POINT (1603278.2522754562 6464030.13553264)",
        "POINT (1603304.896049631 6463958.075765142)",
        "POINT (1603264.5876622554 6463903.927670779)",
    ]
)
voronoi = shapely.get_parts(shapely.voronoi_polygons(shapely.union_all(points)))
clipped = shapely.intersection(voronoi, geom)
symmdiff = shapely.union_all(clipped).symmetric_difference(geom)
symmdiff.area
# 2.1684507522934382e-08
```

Visually:

geom:
<img width="224" alt="Screenshot 2024-06-13 at 23 17 05" src="https://github.com/libgeos/geos/assets/36797143/9784fcb1-f3dc-4f59-985f-17e7e4de93c6">

output of voronoi:
<img width="223" alt="Screenshot 2024-06-13 at 23 17 33" src="https://github.com/libgeos/geos/assets/36797143/d1be3b55-6e6b-47c1-adcf-4062779ca87f">

clipped:
<img width="211" alt="Screenshot 2024-06-13 at 23 18 17" src="https://github.com/libgeos/geos/assets/36797143/9d64389c-36ea-49b5-bb76-0da8ee14b849">

symmdiff:
<img width="204" alt="Screenshot 2024-06-13 at 23 16 50" src="https://github.com/libgeos/geos/assets/36797143/4d4baf06-cad8-4c9b-9e5d-23aaa93c0f35">

My expectation is that the boundary in this case matches, hence the symmetric difference is an empty polygon. In the use case linked above, we do tessellation within many geometries in a coverage but due to this issue, the result is not a valid coverage and the spatial contiguity is broken.

Using GEOS 3.12.1 via shapely 2.0.3.

**Comment by pramsey** [comment]
No, you've introduced new vertices where the voronoi edges hit the boundary edges, so the old and new boundaries won't be the same. New vertices have to fit into the precision grid of the underlying numeric format (IEEE doubles in this case), they do not fall into the precise "rational number line" location you are thinking of.

**Comment by theroggy** [comment]
For illustration, as @pramsey wrote, at the crossings marked with red circles in the image below a new point will be calculated. Due to non-infinite precision, in many cases this point will not be "exactly" on the crossing... so if you overlay with the original polygon in this case you'll get gaps/slivers that are in my experience always narrower than 1e-8.

2 options: 
- if you run `set_precision` on the result of the overlay those slivers will be cleaned up. This is what I always do in practice.
- make the data topologically sound, so make sure that such calculated points are also added to neighbouring polygons. If the points are introduced in the neighbours, the edges fit perfectly and there will no gaps or slivers. Hopefully GEOSCoverageMakeValid is on the way to support this ;-)...

<img width="269" alt="image" src="https://github.com/libgeos/geos/assets/1565789/bf9249ff-1ebf-4afb-95e2-3e5976f44ad6">
