### ISSUE TITLE
RelateNG DE9IM regression

### ISSUE THREAD

**Issue by pramsey** [libgeos/geos#1147]
```
./bin/geosop \
  -a 'LINESTRING(40 180,140 180)' \
  -b 'MULTIPOLYGON(((20 320,180 320,180 180,20 180,20 320)),((60 180,60 80,180 80,180 180,60 180)))' \
  relate
```
Returns on master
```
111F0F212
```
Historic values (seems right)
```
11F00F212
```
Similarly 
```
./bin/geosop \
 -a 'LINESTRING(40 180,140 180)' \
 -b 'MULTIPOLYGON(((20 320,180 320,180 180,20 180,20 320)),((20 180,20 80,180 80,180 180,20 180)))' \
 relate

1FFF0F212
```
Should be `1FF0FF212`

**Comment by dr-jts** [comment]
In both cases (here's the first one)
<img width="200" alt="image" src="https://github.com/user-attachments/assets/4fb8921c-b4b2-4d2c-bc22-1dac30f14b91">

the MultiPolygon is invalid.  If it is converted to a GeometryCollection the result is as expected and as provided by the old GEOS.

The contract for Relate is that the inputs must be valid.  If it's desired to handle invalid MultiPolygons as well then this will likely slow the processing of valid MultiPolygon inputs, since they will need to use the more general but slower approach used for GeometryCollections.

**Comment by mwtoews** [comment]
Should `TopologyException` be raised as (sometimes) before? I know that `isValid` is not always called before, but somehow this was sensed with the previous release.

E.g. compare the behaviour of 3.12.2 vs. 3.13.0beta1 with a single invalid polygon (inner ring is outside exterior):
```bash
$ cat > invalid.wkt
POLYGON ((40 100, 80 100, 80 60, 40 60, 40 100), (60 60, 80 60, 80 40, 60 40, 60 60))
$ ./geos-3.12.2/bin/geosop -a invalid.wkt -b invalid.wkt relate
Run-time exception: TopologyException: side location conflict at 60 60. This can occur if the input geometry is invalid.
$ ./geos-3.13.0beta1/bin/geosop -a invalid.wkt -b invalid.wkt relate
2FFF1FFF2
$ ./geos-3.13.0beta1/bin/geosop -a invalid.wkt -b invalid.wkt equals
true
```
I naively thought RelateNG was more tolerant with invalid inputs, as they appear correct.

And certainly, `makeValid` will make a GeometryCollection that will yield expected results with 3.12.2 and 3.13.0beta1:
```
$ ./geos-3.12.2/bin/geosop -a invalid.wkt makeValid > valid.wkt
$ ./geos-3.12.2/bin/geosop -a valid.wkt -b valid.wkt relate
2FFF1FFF2
$ ./geos-3.12.2/bin/geosop -a valid.wkt -b valid.wkt equals
true
```

**Comment by dr-jts** [comment]
> Should `TopologyException` be raised as (sometimes) before? 

The strategy used in JTS is to not check validity before executing operations, since this often reduces performance.  Instead, this is left to the caller if the call context might provide invalid input.   Some operations can detect invalidity as a result of the operation processing, but this is merely a lucky artifact.

So my take is that RelateNG is operating to spec, and that this test should be deleted from the PostGIS test suite.

@pramsey thoughts?
