### ISSUE TITLE
MinimumBoundingCircle::pointWithMinAngleWithSegment needs to protect index access

### ISSUE THREAD

**Issue by hobu** [libgeos/geos#261]
`pointWithMinAngleWithSegment` references into a Coordinate array without checking if it can do it.
  
```
	double minAng = std::numeric_limits<double>::max();
	if (pts.size() > 1)
		const Coordinate* minAngPt = &pts[0];
	else
		return Coordinate::getNull();
```

**Comment by dbaston** [comment]
It's clear from looking at the code that `MinimumBoundingCircle::pointWithMinAngleWithSegment` is never called when `pts.size() < 1`. I think I'd just add `assert(!pts.empty())` at the top of the method to quiet the static analyzer, instead of adding a check for a situation that never happens and risking confusing the reader by suggesting the the method could return a null Coordinate.
