### ISSUE TITLE
CMake build does not install symlinks for libgeos.so.<version>

### ISSUE THREAD

**Issue by Kirill888** [libgeos/geos#272]
Using 3.8.0 release tar ball from github and using cmake:

```
mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
make install
```

Symlink to `libgeos_c.so.1.13.1` are installed but not for `libgeos.so.3.8.0`, note that symlink is present in the `build/lib` folder but doesn't get copied into `/usr/lib/` by `make install`

```
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libgeos.so.3.8.0
-- Installing: /usr/local/lib/libgeos_c.so.1.13.1
-- Installing: /usr/local/lib/libgeos_c.so.1
-- Set runtime path of "/usr/local/lib/libgeos_c.so.1.13.1" to ""
-- Installing: /usr/local/lib/libgeos_c.so
...
```

I'm using cmake 3.16.0 on Ubuntu 18.04

```
cmake --version
cmake version 3.16.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by strk** [comment]
Please report your issue on geos.osgeo.org

**Comment by pramsey** [comment]
This is by design.

https://github.com/libgeos/geos/commit/a71e095d304d13c071e5144f128fe37680e6c47b

Basically, since we are not making semver guarantees for the C++ libraries (in particular, ABI compatibility doesn't even always cross over on patch release, though it mostly does we don't check), we aren't including symlinks that would allow people to take advantage of those (non-existent) guarantees.
