### ISSUE TITLE
Allow construction of LinearRings with < 4 points

### ISSUE THREAD

**Issue by dbaston** [libgeos/geos#406]
If we can't construct them, we can't repair them. As discussed at https://github.com/r-spatial/sf/issues/1589 and https://github.com/locationtech/jts/issues/558

**Comment by dr-jts** [comment]
The minimum number of points in a LinearRing can definitely be reduced to 3, instead of 4.  That will handle the data in both issues above.  I haven't seen any data which requires a lower limit, so probably best to make the minimal change for now.

**Comment by dr-jts** [comment]
See JTS PR [682](https://github.com/locationtech/jts/pull/682).

**Comment by jratike80** [comment]
I wonder what MakeValid should do. To remove the flat ring that does not have any area, or to maintain the topology by creating a minimal buffer or by adding a fourth point with a small offset?

**Comment by dr-jts** [comment]
> I wonder what MakeValid should do. To remove the flat ring that does not have any area, or to maintain the topology by creating a minimal buffer or by adding a fourth point with a small offset?

That's a very timely question, since I'm working on a `GeometryFixer` class for JTS (for eventual port into GEOS, since it has slightly different semantics to `MakeValid`.  I'm not sure there's an obvious right answer.  I do NOT think that the flat ring should be buffered or have points added, however, for reasons of performance and (more importantly) avoidance of introducing unexpected coordinates.

So the options for fixing a ring with too few points seem to be:
- turn it into a `LineString` or a `Point`
- turn it into a `LINEARING EMPTY`

There is the same issue for a ring with many points but which is flat, and a LineString with too few points.

Another approach I am considering is that if the ring (or line) is an atomic geometry, then reduce it to a geometry of inherent dimensional type; OR if if the ring/line is part of a collection, then drop it.  This avoids creating collections of mixed type, which are awkward to handle.

Feedback welcome.

**Comment by jratike80** [comment]
When I think where I have met such geometries, OpenStreetMap data has always had them for some reason, and at least some MVT vector tile writers degenerate rings into straight lines occasionally. As a user of the data I would probably appreciate to have an option to get placeholders for locating those places because originally they may have been meaningful. `POINT` would do for that purpose. `LINEARRING EMPTY` is theoretically fine but otherwise useless, I think.

My main vector tool is OpenJUMP so I do not fear collections, but for most GIS users they are complicated.

**Comment by dr-jts** [comment]
@jratike80 Sounds like there needs to be some options for users to use when making valid geometries.  At least one to indicate whether to drop collapsed elements, or to preserve them as lower-dimension elements.
