### ISSUE TITLE
Any plans to make the C++ API stable? 

### ISSUE THREAD

**Issue by oleg-alexandrov** [libgeos/geos#469]
I know that the C++ API for GEOS is unstable. That is a headache for people who package software with many dependencies, to say the obvious. 

Here, https://trac.osgeo.org/geos/wiki/RFC6, it was stated by Regina Obe that "we do not have the manpower to guarantee ABI or API compatibility from minor version to minor version and thus using it in an environment where the GEOS library is shared across many software is unsupported. We are also planning significant refactoring in GEOS 3.8 which will very likely break the C++ API".

Yet now that already version 3.9.1 has been out, I wonder if there are any plans to stabilize the C++ API.  I am aware of the tension between stability and the desire to grow, also about issues of manpower in open-source projects. 

My apologies if this is not the right forum for this. I've been looking around for a while but could not find recent discussions of this issue or a better venue.

**Comment by dr-jts** [comment]
There are no plans for making the C++ API stable.  The reasons for not doing so have not changed.

**Comment by dbaston** [comment]
The first step would be to define what "the API" is. Every public method? That'll never stabilize. Public methods of `Geometry` ? No policy around, it, but it is effectively stable with the exception of transitioning to `unique_ptr` in ~3.7.

**Comment by oleg-alexandrov** [comment]
There is a chance I am missing something about what makes GEOS unique.

As far as I know, foundational libraries, that is, those that are used in a large number of projects (and those projects make use of many tens of other such libraries), tend to use great care when it comes to breaking things for others. Sure sometimes things have to break, the most notable example being the transition from Python 2 to 3, which involved untold amount of developer man-hours across the whole world to deal with.

I am a bit surprised OSGEO matter-of-factly tells users that, if they want to use the C++ API, that's their problem to deal with things always breaking. 

My perspective is the one of a system integrator. Each needed library is a little brick. OSGEO is used in a package which is used by another package which is used by my own package. The dependencies are managed with conda. Each time one such little brick refuses to behave the whole thing fails to work and a lot of time is spent trying to see what can be done about this. 

Your perspective, of a developer trying to make the best use of one's time given the large amount of work to do and the great useful value you believe your work provides is likely rather different.

**Comment by hobu** [comment]
> I am a bit surprised OSGEO matter-of-factly tells users that, if they want to use the C++ API, that's their problem to deal with things always breaking.

This has become the policy due to some of the developers of GEOS not wishing to take care to provide any C++ API compatibility due to the time and care costs associated with it, and the headaches a compatibility constraint can cause for design choices of the software. 

The way to deal with it is not to try to convince the GEOS PSC that they should value C++ compatibility. You wont. Write your own software to provide an indirection over the GEOS C++ API that insulates you from the changes.

I'm fine with the no promise of compatibility without the childish warning and `#ifdef` needed to use the API that's currently implemented. It demonstrates a lack of regard that some of the GEOS developers have for a segment its userbase – a userbase that is almost always **other developers**.
