### ISSUE TITLE
Add Hilbert code to C API

### ISSUE THREAD

**Issue by brendan-ward** [libgeos/geos#553]
In the Geopandas / shapely ecosystem, there is an interest in calculating Hilbert curve codes for geometries.  Currently this is based on the centroid of a geometry's extent, but someday may be some other representative point.

It looks like it should be straightforward to add parts of `HilbertCode` / `HilbertEncoder` C++ APIs to the C API, but I wanted to get some feedback first before opening a PR.

I think we may want to expose 2 API functions (`_r` and context handle omitted for clarity):

1) `int GEOSHilbert(GEOSGeometry* geom, unsigned int level)`: 
gets envelope, creates `HilbertEncoder` and calls `HilbertEncoder::encode()`.  Return -1 on error since otherwise Hilbert codes should be unsigned 32 bit integers.

This is convenient for our current usage in that we don't first have to do separate calls to GEOS obtain the bounding coordinates and derive the midpoint.

I'm assuming empty geometries should return -1.

2) `int GEOSHilbert_xy(unsigned int x, unsigned int y, unsigned int level)`: 
calls `HilbertCode::encode()`

This provides a more general case that could be used for any arbitrary x,y.

Any opposition to that plan?

Crossref: https://github.com/geopandas/geopandas/pull/2297

/cc @jorisvandenbossche 

(edited to fix that x,y parameters are unsigned ints not doubles; user must have already scaled their double coords to ints before calling)

**Comment by pramsey** [comment]
> Return -1 on error since otherwise Hilbert codes should be unsigned 32 bit integers.

This is problematical, since you can't return -1 in an unsigned 32 bit integer. Maybe instead, 
```
int GEOSHilbert(GEOSGeometry* geom, unsigned int level, unsigned int hilbert)
```
Where the return value is a status. For example, here's the signature for GEOSArea
```
extern int GEOS_DLL GEOSArea(
    const GEOSGeometry* g,
    double *area);
```

**Comment by brendan-ward** [comment]
> you can't return -1 in an unsigned 32 bit integer

correct, which is why I was thinking of returning a signed `int` instead of `unsigned int`.  Sorry, didn't make it explicitly clear that there would be a step between the internal calls to `encode()` (which return unsigned) and the final return (which would have returned signed).

However, I like your suggest of int status return better: 0 on error, 1 on success.

**Comment by jorisvandenbossche** [comment]
> 1. `int GEOSHilbert(GEOSGeometry* geom, unsigned int level)`:
>        gets envelope, creates `HilbertEncoder` and calls `HilbertEncoder::encode()`.

Would this create the `HilbertEncoder` and call `HilbertEncoder::encode()` with the same envelope? (since [both](https://github.com/libgeos/geos/blob/70d2111bd66ea848809e5738896256199d9a7cba/src/shape/fractal/HilbertEncoder.cpp#L29-L51) accept an envolope) 
In practice (eg for the geopandas use case of calculating the hilbert codes for a set of geometries), we will want to instantiate the `HilbertEncoder` with an accumulated envelope. 

Looking at the code here, it seems there is actually a `HilbertEncoder::sort(std::vector<geom::Geometry*>& geoms)` sort method that takes a vector of geometries and basically does this for you (first getting the overall envelope, instantiating the HilbertEncoder with that, and then passing the individual envelopes to encode:

https://github.com/libgeos/geos/blob/70d2111bd66ea848809e5738896256199d9a7cba/src/shape/fractal/HilbertEncoder.cpp#L56-L86

So some other ideas of a potential signature for the C API:

* `GEOSHilbert(GEOSGeometry* geom, GEOSGeometry* extent, unsigned int level, unsigned int* code)`  
  which takes a second geometry that is used for instantiating the HilbertEncoder (this might have the advantage that it needs to instantiate this HilbertEncoder on every repeated call, although this is probably quite cheap)
* `GEOSHilbert(GEOSGeometry** geoms, unsigned int ngeoms, unsigned int level, unsigned int** codes)`  
  which takes an array of geometries as input, and like the `HilbertEncoder::sort` first calculates the total extent, instantiates the `HilbertEncoder` with that, and returns an array of codes.

There is prior art in C APIs that have an array of geometries as input, but I think they all still are like "scalar" functions in that they eg create a single object from this array of geometries (for example `GEOSGeom_createCollection`). So a function like the second bullet point that operates on an array of geometries and returns an array as result would be a new idiom (no idea if that's something GEOS wants to start doing).

**Comment by brendan-ward** [comment]
Thanks the for the feedback @jorisvandenbossche 

I had totally forgotten to account for passing in the envelope to be used for scaling and then got caught up in trying to decide if it was better to pass in the envelope as a geometry (a little more overhead to construct on our part) vs xmin, ymin, xmax, ymax.

> `GEOSHilbert(GEOSGeometry** geoms, unsigned int ngeoms, unsigned int level, unsigned int** codes)`

I'm assuming that if any geometry were empty or otherwise not representable using Hilbert, that the function would return an error (as described above), rather than invalid Hilbert codes for those geometries.

My hunch is that adopting a "vectorized" (array-in, array-out) API for GEOS is a bigger discussion, so starting with `GEOSHilbert(GEOSGeometry* geom, GEOSGeometry* extent, unsigned int level, unsigned int* code)` (or xmin, ymin, xmax, ymax equivalent) seems like a reasonable start here.


In my `GEOSHilbert_xy(unsigned int x, unsigned int y, unsigned int level)`, I'm assuming the caller is responsbile for all scaling, but I'm wondering now if that should get handled here as well, so something like

```
GEOSHilbert_xy(double x, double y, double xmin, double, ymin, double xmax, double ymax, unsigned int level)
```

Then the caller only needs to pass in their raw coordinates and extent coordinates for scaling.  Otherwise, it is maybe less useful, since it is really just providing an interface into the underlying Hilbert calculation but not particularly interesting from a geometry standpoint.

**Comment by pramsey** [comment]
By the time you're passing in the extents as well as the coordinates all in double you're only a short function call away from just calculating the Hilbert code yourself. This sig seems OK
```
GEOSHilbert(GEOSGeometry* geom, GEOSGeometry* extent, unsigned int level, unsigned int* code)
```
