### ISSUE TITLE
Feature Request: Add flag to close polygons automatically, instead of throwing llegalArgumentException

### ISSUE THREAD

**Issue by Cameronsplaze** [libgeos/geos#587]
# Details of feature

Especially with a nested GeometryCollection, and a open polygon deep inside a wkt, it's not trivial to close polygons without help from libraries like this one. Is there some way to force the library to load it, to let us interact with the wkt?

```python
# Using shapely, since they use this library behind the scenes, and it's what I know how to use
from shapely import wkt
wkt.loads("POLYGON ((0 0, 1 0, 1 1, 0 1))") # missing the last "0 0"
llegalArgumentException: Points of LinearRing do not form a closed linestring
```
# Proposal

One idea is to add a `strict=True`, that the user can switch to False if they hit this too. (Theoretically exposing this feature to shapely). This will let the user decide how to repair it.
*OR*
Add a `repair=False` flag, that if flipped, will close the linestring automatically instead. (And other possible repairs that are common).

```python
from shapely import wkt
poly = wkt.loads("POLYGON ((0 0, 1 0, 1 1, 0 1))", repair=True)
print(poly.wkt)
# If you repair automatically
'POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))'
# If you set "strict=False", letting the user decide how to repair it
'POLYGON ((0 0, 0 1, 1 1, 1 0))'
```

**Comment by pramsey** [comment]
Repair like also fix invalidity?

**Comment by dr-jts** [comment]
Seems like a reasonable enhancement.  

I suggest only adding a flag to close open rings.  This is basically just a syntactic fix, and it's required to read the geometry in at all.  

Any further repair can already be done with existing functions, so no need to duplicate it in the WKT reader.

**Comment by dr-jts** [comment]
Yes, this behaviour (or lack of) is the same in JTS.  Odd that no-one has requested this there - it would be very handy in some situations.  In fact I might add it.

**Comment by Cameronsplaze** [comment]
> I suggest only adding a flag to close open rings. This is basically just a syntactic fix, and it's required to read the geometry in at all.

Sounds great! This would solve my use case as well.

> I think we get this from JTS ... Yes, this behaviour (or lack of) is the same in JTS

Is JTS a library that geos uses? If so, I'd be down to open another issue there if it helps.

**Comment by pramsey** [comment]
GEOS is a C++ port of JTS. http://libgeos.org/usage/faq/#why-does-geos-follow-jts-design

**Comment by dr-jts** [comment]
Actually there might be a bit more that can be done here.  The reader could also "pad out" the input to ensure that coordinate sequences are long enough to pass the constructor validation.  E.g. perhaps Polygon rings should be padded out to ensure they have length >= 4 ?  They'd still be invalid of course, but at least would be structurally correct.

Not sure what length checks are in place in GEOS, so need to confirm this.

**Comment by dr-jts** [comment]
I'm working on adding this to JTS, BTW.  So that can provide a pattern to follow.

**Comment by dr-jts** [comment]
[JTS-848](https://github.com/locationtech/jts/pull/848) adds `WKTReader.setFixStructure`.

**Comment by pramsey** [comment]
Same for WKBReader?

**Comment by dr-jts** [comment]
> Same for WKBReader?

Might as well, although I'm guessing this occurs less frequently with WKB, since's it's probably emitted by systems which Do The Right Thing.

**Comment by strk** [comment]
> @strk? Any ideas?

Folliwng JTS strictly..

**Comment by pramsey** [comment]
Ugh. So, on the one hand, can add this fix into WKTReader. And the WKBReader. But then annoyingly, all the pre-checks and machinery have to remain in PostGIS, because when you instantiate a geometry with a coordinate sequence, the code checks for ring closure. Like, the place to address this (really) is that shared moment, when you go new LinearRing(CoordinateSequence). Fix it there, and all inputs and even API-based construction is covered. Trouble is... by the time we get there CoordinateSequence is immutable.

Still, I think even making a fresh, closed copy of a ring during construction of the polygon would be relatively cheap (only happens when ring is not closed to start with) and could cover all cases. In that case the `isFix` boolean would reside on the GeometryFactory instead of on all the various readers.

**Comment by dr-jts** [comment]
> Still, I think even making a fresh, closed copy of a ring during construction of the polygon would be relatively cheap (only happens when ring is not closed to start with) and could cover all cases. In that case the `isFix` boolean would reside on the GeometryFactory instead of on all the various readers.

Hmm...  have to think about this.  Somehow doesn't feel quite right to have an `isFix` flag on `GeometryFactory`.  But perhaps that is the only way to inject that behaviour automatically so that it can apply everywhere.  Or could it reside on C constructor functions that create rings?

**Comment by dbaston** [comment]
I'd be inclined to leave the settings on the readers, since we already have C API functions for setting various properties of the readers. GeometryFactory isn't exposed to the C API. Unlike the callers of WKTReader and WKBReader, a caller that is creating a coordinate sequence in the C API is in a position to create a proper ring in the first place.

**Comment by Cameronsplaze** [comment]
Just out of curiosity, is this functionality still on the table and/or in progress?

**Comment by dr-jts** [comment]
> Just out of curiosity, is this functionality still on the table and/or in progress?

Still on the table, but not in progress...  :(
