### ISSUE TITLE
Invalid convex hull with close MultiPoint pairs

### ISSUE THREAD

**Issue by mwtoews** [libgeos/geos#722]
Found via https://github.com/shapely/shapely/issues/1593
```
$ geosop -a "MULTIPOINT (-0.2 -0.1, 1.38777878e-17 -0.1, 0.2 -0.1, -1.38777878e-17 -0.1, -0.2 0.1, 1.38777878e-17 0.1, 0.2 0.1, -1.38777878e-17 0.1)" convexHull -f wkt
POLYGON ((-0.2 -0.1, -0.2 0.1, 0.2 0.1, 0 -0.1, 0 -0.1, 0.2 -0.1, -0.2 -0.1))
```
![image](https://user-images.githubusercontent.com/895458/199355324-b484cb06-ef8c-49e6-8ab2-e8fc1f6ad7a6.png)
the input has eight unique points, but two pairs are really close, so it looks like six.

Furthermore, these eight points can be sorted differently to yield the expected result:
```
$ geosop -a "MULTIPOINT (-0.2 -0.1, -0.2 0.1, -1.38777878e-17 -0.1, -1.38777878e-17 0.1, 1.38777878e-17 -0.1, 1.38777878e-17 0.1, 0.2 -0.1, 0.2 0.1)" convexHull -f wkt
POLYGON ((-0.2 -0.1, -0.2 0.1, 0.2 0.1, 0.2 -0.1, -0.2 -0.1))
```

**Comment by dr-jts** [comment]
Fails in JTS too.  More investigation needed.

**Comment by dr-jts** [comment]
In JTS the following simpler geometry also produces the invalid result:
```
MULTIPOINT ((-0.2 -0.1), (0 -0.1), (0.2 -0.1), (-0 -0.1), (-0.2 0.1), (0 0.1), (0.2 0.1), (-0 0.1))
```
So (somewhat shockingly) it looks like the ConvexHull algorithm doesn't handle collinear vertices correctly.  Hopefully this will be an easy fix.

**Comment by dr-jts** [comment]
As expected, it's a robustness issue.  The Convex Hull Graham Scan algorithm depends on having vertices sorted radially and by increasing distance around the "lowest" input vertex.  It turns out that the two bottom vertices which are very close together sort incorrectly (they are computed as equal instead of one being lower than the other).  

Hopefully it will be possible to improve the distance test to have these values sort correctly.  (This is straightforward for cases like this where the coordinates lie along a vertical or horizontal line, but it would be nice to have a solution which accommodates vertices along a diagonal line.)
