### ISSUE TITLE
Run-time exception with difference op after removal of old overlay engine

### ISSUE THREAD

**Issue by mwtoews** [libgeos/geos#797]
Since #788 a new runtime exception is encountered:
```
$ ./bin/geosop -f wkt -a "GEOMETRYCOLLECTION(POINT(51 -1), LINESTRING(52 -1, 49 2))" -b "POINT(2 3)" difference
Run-time exception: IllegalArgumentException: Overlay input is mixed-dimension
```
and same also with differenceSR.

Previous behaviour was:
```
$ ./bin/geosop -f wkt -a "GEOMETRYCOLLECTION(POINT(51 -1), LINESTRING(52 -1, 49 2))" -b "POINT(2 3)" difference
GEOMETRYCOLLECTION (POINT (51 -1), LINESTRING (52 -1, 49 2))
```

**Comment by dbaston** [comment]
I think the GEOS support for mixed-dimension overlay may be accidental -- the [docs](https://github.com/libgeos/geos/blob/main/include/geos/geom/Geometry.h#L712) say that it should raise an exception. And it apparently has no tests, or removing the support would have caused a failure.

Some more background is in https://trac.osgeo.org/geos/ticket/755 and https://trac.osgeo.org/geos/ticket/1092

Should we:
- Do nothing, and continue to produce the error,
- Extend OverlayNG to handle these cases, or
- Maintain a second overlay engine with no tests or documented semantics to handle these cases ?

**Comment by dr-jts** [comment]
It would be nice to know how the old code handled mixed-type collections.  And how far the support goes (e.g. does it handle subtracting a line from a line and point which are overlapped?). (I wonder if the `HeuristicOverlay` just kept reducing precision until it produced a totally garbage answer, which just happens to be right in this case?)

Extending OverlayNG to handle this is going to be a significant piece of work, so not a short-term solution.

My vote is to keep producing the error, as originally intended and as implemented in the current code.

**Comment by dr-jts** [comment]
For the record, at the moment I think the way to implement OverlayNG support for mixed collections is to run a series of overlay ops on sub-collections of elements of same dimension, and then combine the results.  This needs to be preceded by a union of each input to make them non-overlapping.

For example, for intersection the result is the intersection of each combination of areas, lines, points from A against the areas, lines and points of B (once A and B have been made non-overlapping).

This is a lot of overlap ops, but in many cases some of them can be omitted due to empty or disjoint sub-collections.

**Comment by strk** [comment]
Here's a real world example of the heuristic overlay reducing precision up to garbage answer: https://trac.osgeo.org/postgis/ticket/5401

**Comment by pramsey** [comment]
I think that #924 is a different problem than this (the precision reduction). Let's keep this just about handling mixed-dimension collections (which I'm about to merge a fix for).
