### ISSUE TITLE
CoverageUnion CAPI regression

### ISSUE THREAD

**Issue by mwtoews** [libgeos/geos#904]
I'm seeing a regression in shapely from bd42a68a09ae9001a66ad4e1a82cd563639ef30b where "CoverageUnion cannot process incorrectly noded inputs" is not raised with two inputs:

- `POLYGON ((1 1, 1 0, 0 0, 0 1, 1 1))`
- `POLYGON ((1 0, 0.9 1, 2 1, 2 0, 1 0)))`

![image](https://github.com/libgeos/geos/assets/895458/db550058-7434-4c28-a9a1-098002dc1ee7)

This can be somewhat replicated with the C++ API comparing coverageUnionNG vs coverageUnion:
```bash
$ ./bin/geosop -a "GEOMETRYCOLLECTION (POLYGON ((1 1, 1 0, 0 0, 0 1, 1 1)), POLYGON ((1 0, 0.9 1, 2 1, 2 0, 1 0)))" coverageUnionNG -f txt
MULTIPOLYGON (((1 0, 0 0, 0 1, 1 1, 1 0)), ((0.9 1, 2 1, 2 0, 1 0, 0.9 1)))
$ ./bin/geosop -a "GEOMETRYCOLLECTION (POLYGON ((1 1, 1 0, 0 0, 0 1, 1 1)), POLYGON ((1 0, 0.9 1, 2 1, 2 0, 1 0)))" coverageUnion -f txt
Run-time exception: TopologyException: CoverageUnion cannot process incorrectly noded inputs.
```

**Comment by mwtoews** [comment]
Or (reading the change commit again) it is a change in behaviour, where the collection is returned unchanged (except for, perhaps, a minor change from GeometryCollection to MultiPolygon). Is this the new expected behaviour?

**Comment by dr-jts** [comment]
This is the expected behaviour.  The new `coverage.CoverageUnion` algorithm doesn't detect invalid inputs, because doing so would essentially require a full coverage validation, which is much slower than the union itself.    The client needs to confirm the input is a valid coverage in order to get a correct result.

The "area check" heuristic that was [added](https://github.com/libgeos/geos/commit/bd42a68a09ae9001a66ad4e1a82cd563639ef30b#diff-60ff4b2c359cef488388033ceaf25f0f1fbb6c4b1879bbd54ac1f185d5abb693R52) to `coverage.CoverageUnion` doesn't solve this problem, because the `coverage.CoverageUnion` algorithm doesn't produce different areas for invalid inputs.  (@dbaston this is because the algorithm doesn't use `Polygonizer`).  That heuristic should actually be removed, to simplify the code.

**Comment by mwtoews** [comment]
Thanks for the "valid" details!
 
Other regressions are related to geometry combinations. Before coverageUnion would simply raise "Unhandled geometry type in CoverageUnion", but now there are different results. For sake of simplicity, here are some of them with geosop:
```bash
$ ./bin/geosop -a "GEOMETRYCOLLECTION (POINT (2 3), POINT (2 3))" coverageUnionNG -f wkt
POINT EMPTY
$ ./bin/geosop -a "GEOMETRYCOLLECTION (POINT (2 3), MULTIPOINT (0 0, 1 2))" coverageUnionNG -f wkt
POINT EMPTY
$ ./bin/geosop -a "GEOMETRYCOLLECTION (LINESTRING (0 0, 1 0, 1 1), LINESTRING (0 0, 1 0, 1 1))" coverageUnionNG -f wkt
MULTILINESTRING ((0 0, 1 0), (1 0, 1 1))
$ ./bin/geosop -a "GEOMETRYCOLLECTION (LINESTRING (0 0, 1 0, 1 1), MULTILINESTRING ((0 0, 1 2)))" coverageUnionNG -f wkt
MULTILINESTRING ((0 0, 1 0), (1 0, 1 1), (0 0, 1 2))
$ ./bin/geosop -a "GEOMETRYCOLLECTION (MULTILINESTRING ((0 0, 1 2)), LINESTRING (0 0, 1 2))" coverageUnionNG -f wkt
LINESTRING (0 0, 1 2)
$ ./bin/geosop -a "GEOMETRYCOLLECTION (LINESTRING (0 0, 1 2), LINESTRING (0 0, 1 2))" coverageUnionNG -f wkt
LINESTRING (0 0, 1 2)
```
do these look expected?

**Comment by dr-jts** [comment]
Actually yes, those results are expected.  CoverageUnion has the undocumented behaviour of unioning linear networks as well.

It should probably be enhanced to throw an error on Point inputs, however.  They aren't supported in any meaningful way.

**Comment by pramsey** [comment]
I think this is a "leave as is" situation, as we cannot replicate the old behaviour but we like the new approach.

**Comment by dbaston** [comment]
I think this should probably be noted in `NEWS`, something like "GEOSCoverageUnion now gives an incorrect result instead of an error on inputs that do not form a proper coverage; to avoid this, check coverage using GEOSCoverageisValid before calling GEOSCoverageUnion"
