### ISSUE TITLE
Crash on large but finite floats on macOS

### ISSUE THREAD

**Issue by RichardBowenGM** [libgeos/geos#970]
(from the downstream bug: https://github.com/shapely/shapely/issues/1903 )

## Problem description

I am getting an abort on large-but-finite floats, a small example is:

```shell
richard@Richards-MacBook-Pro-2 ~ % geosop -a "POINT (1e+279 0)" -f wkt
zsh: abort      geosop -a "POINT (1e+279 0)" -f wkt
```

going down a factor of ten works:

```shell
richard@Richards-MacBook-Pro-2 ~ % geosop -a "POINT (1e+278 0)" -f wkt
POINT (100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 0)
```

and in fact infinity also works:
```shell
% geosop -a "POINT (Infinity 0)" -f wkt
POINT (Infinity 0)
```

## Environment

This is `geosop` version 3.12.0, installed through homebrew on Mac OS X 13.4.1.

I originally discovered this testing some python code that uses `shapely` and was only able to reproduce on MacOS. I have not tried to reproduce with `geosop` under linux (will try this reproduction soon). However in the upstream,  @jorisvandenbossche reports also reproducing under linux.

**Comment by pramsey** [comment]
Reproduces here too, but that's not so interesting because I'm OSX too. But you're not alone :)

**Comment by mwtoews** [comment]
I think there should be some limits where scientific formatting should be used instead of positional (via ryu). I'll "float" some examples of these limits when I get a chance.

**Comment by mwtoews** [comment]
The root cause is with a fixed 128-byte buffer:
https://github.com/libgeos/geos/blob/28d70a2e4582edcd3625659f70e31d1853423875/src/io/WKTWriter.cpp#L420

but I don't think the solution is increasing this size to an arbitrary bigger number. According to [Wikipedia](https://en.wikipedia.org/wiki/Double-precision_floating-point_format), doubles have from 15 to 17 [significant decimal digits](https://en.wikipedia.org/wiki/Significant_figures) precision. I'll need to think a bit more about a suggestion for numbers that would be better formatted as scientific, considering the "trim" option too.

A work-around is to disable "trim" by setting precision:
```bash
$ geosop -a "POINT (1e+279 0)" -f wkt -p 0
POINT (1000000000000000057973292274960393763265862568545700036605220385651388108719182436946549269568487016710341006018846736433592448182900184244384740055240373818548092825496324683715486704619720031476992256475264028209364937790149360843820835266007499279518823345374529865067232493568 0)
```
(this also shows the 17 significant decimal digits too)

**Comment by caspervdw** [comment]
FWIW, on Linux (Ubuntu 22.04) it crashes already at 1e+136.

```
protected = may_segfault(shapely.to_wkt)
for i in range(1, 1000):
    try:
        protected(shapely.points([10.0**i, 0.]))
    except OSError:
        break
print(f"Crashed at 1E+{i}")
```

**Comment by mwtoews** [comment]
I'd rather not see any error, personally. I think if precision is not set (i.e. it is -1) and trim is set to true (the new defaults) then the best precision should be used for float formatting. There are a few tipping points when positional and scientific are used. 

Here with CPython:
```python
# big numbers
float('1.234567890123456789e15')  # 1234567890123456.8
float('1.234567890123456789e16')  # 1.2345678901234568e+16
# small numbers
float('1.234567890123456789e-4')  # 0.00012345678901234567
float('1.234567890123456789e-5')  # 1.2345678901234568e-05
```
so one my my suggestions is to positional formatting for abs(val) greater than or equal to 1e-4 and less than 1e16, which is honestly most numbers that we see for coordinates. Otherwise for very large and small numbers, scientific formatting should be used. For the "trim" option use ryu's `geos_d2sexp_buffered_n`
https://github.com/libgeos/geos/blob/28d70a2e4582edcd3625659f70e31d1853423875/src/deps/ryu/ryu.h#L32-L35
I'm slowly sorting out a patch, maybe ready later this week.
