### ISSUE TITLE
Hausdorff distance wrong for LinearRing

### ISSUE THREAD

**Issue by mwtoews** [libgeos/geos#987]
Originally reported https://github.com/shapely/shapely/issues/1934

Three geometry types with the same coordinates yield different Hausdorff distances, when the expected result should be the same (as JTS does).

Testing against main:
```bash
$ ./bin/geosop -a "POLYGON ((0 0, 0 10, 10 10, 10 0, 0 0))" -b "POLYGON ((1 1, 1 9, 9 9, 9 1, 1 1))" hausdorffDistance
1.4142135623730951
$ ./bin/geosop -a "LINESTRING (0 0, 0 10, 10 10, 10 0, 0 0)" -b "LINESTRING (1 1, 1 9, 9 9, 9 1, 1 1)" hausdorffDistance
1.4142135623730951
$ ./bin/geosop -a "LINEARRING (0 0, 0 10, 10 10, 10 0, 0 0)" -b "LINEARRING (1 1, 1 9, 9 9, 9 1, 1 1)" hausdorffDistance
12.727922061357855
```
Here is a viz of the expected result via JTS:
![image](https://github.com/libgeos/geos/assets/895458/5b6f3999-a1a0-4c82-8a1e-9b7f744ffdcd)

**Comment by dr-jts** [comment]
This is because the case `geom.getGeometryTypeId() == GEOS_LINEARRING` is not being checked in `DistanceToPoint::computeDistance` [here](https://github.com/libgeos/geos/blob/main/src/algorithm/distance/DistanceToPoint.cpp#L48).
Because of this omission the code drops through to computing the distance to only a single point of the input.

This is the problem with checking typeIds rather than using the inheritance structure.  No doubt there were good reasons for doing this.  It's a simple fix here, of course.   The bigger worry is whether there are other places in the code which need to check for `GEOS_LINEARRING`?  @pramsey thoughts?

**Comment by pramsey** [comment]
Could do an audit to look for suspect patterns? The inheritance level checks had a big performance penalty, so they got scrubbed out a few releases ago.

**Comment by mwtoews** [comment]
the "assume geom is Point" part probably should throw an exception if unhandled

**Comment by dr-jts** [comment]
> Could do an audit to look for suspect patterns? The inheritance level checks had a big performance penalty, so they got scrubbed out a few releases ago.

Yep, I've had a look. Actually looks pretty clea.  There might be one or two other instances that need to be fixed - I will check further.

**Comment by dr-jts** [comment]
> the "assume geom is Point" part probably should throw an exception if unhandled

Yes, good point.  Like in `PointLocator` [here](https://github.com/libgeos/geos/blob/main/src/algorithm/PointLocator.cpp#L137).

**Comment by dr-jts** [comment]
LinearRings are the red-headed stepchild in JTS/GEOS - they are underrepresented in unit tests (and maybe in some algorithms).

**Comment by mwtoews** [comment]
It seems when this component was ported from JTS' [DistanceToPoint.java](https://github.com/locationtech/jts/blob/85c9391a0446f63208027697b3948b668c2e38b0/modules/core/src/main/java/org/locationtech/jts/algorithm/distance/DistanceToPoint.java#L31-L49), `geom instanceof LineString` was naively interpreted as `geom.getGeometryTypeId() == GEOS_LINESTRING`. This is another suspect pattern, since C++ doesn't have `instanceof` (or [use this](https://stackoverflow.com/questions/500493/c-equivalent-of-javas-instanceof)).

**Comment by dr-jts** [comment]
Actually the port originally [used](https://github.com/libgeos/geos/blob/d271aaa9a1939fe5a51c5b5d05f1a3d547a2f900/src/algorithm/distance/DistanceToPoint.cpp#L43)  the C++ equivalent of `instanceOf`:
```
const LineString* ls = dynamic_cast<const LineString*>(&geom)
```
But this was changed in https://github.com/libgeos/geos/commit/bf2958e713d93a32a70eeb2b37d69bef6892cc0d to use the hand-rolled typeId pattern.  Apparently `dynamic_cast` is slow - which seems unfortunate, since it's such a key part of inheritance-based programming.

**Comment by dr-jts** [comment]
A more geometric-based alternative would be to check if the geometry is atomic (not a collection) and has dimension = 1.  Or perhaps provide a `Geometry.isLine` method to check if it's safe to use `static_cast<const LineString*>`.  

There is 3 situations which can occur (and I _think_ there's instances of all being used in different algorithms):

1. handle both `LineString` and `LinearRing` in the same way
1. handle `LineString` one way and `LinearRing` another
1. handle an open `LineString` one way, and a closed `LineString` and a `LinearRing` in another

Instead of relying on the brittle `typeId` design it might be better to provide methods to distinguish these cases.
