### ISSUE TITLE
Empty LineString created with HasZ() is true

### ISSUE THREAD

**Issue by ddowling** [libgeos/geos#993]
I am trying to track down an issue in recent versions of GeoDjango where empty `LineString` objects are being created with the `hasz` property True. The following code is outputting True with libgeos version 3.12.0_CAPI_1.18.0. When run with 3.11.2-CAPI-1.17.2 the code putputs False

```python
from django.contrib.gis.geos import LineString, geos_version
print(geos_version())
ls = LineString()
print(ls.hasz)
```

I have traced this down to the C `libgeos` API where `GEOSGeom_createLineString` is getting called with a `NULL` argument. 
Following is a short C program that demonstrates this. When run with version 3.12.0 of libgeos it outputs GEOSHasZ() = 1. With version 3.11.0 it outputs GEOSHasZ() = 0.

```c
#include <stdio.h>
#include <stdarg.h>

#include <geos_c.h>

static void geos_msg_handler(const char* fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    vprintf (fmt, ap);
    va_end(ap);
}

int main()
{
    /* Send notice and error messages to the terminal */
    initGEOS(geos_msg_handler, geos_msg_handler);

    printf("GEOS Version %s\n", GEOSversion());

    GEOSGeometry* geom = GEOSGeom_createLineString(NULL);

    GEOSWKTWriter* writer = GEOSWKTWriter_create();
    char* wkt = GEOSWKTWriter_write(writer, geom);
    printf("Geometry: %s\n", wkt);
    printf("GEOSHasZ() = %d\n", GEOSHasZ(geom));

    /* Clean up allocated objects */
    GEOSWKTWriter_destroy( writer);
    GEOSGeom_destroy(geom);

    /* Clean up the global context */
    finishGEOS();

    return 0;
}

````

**Comment by ddowling** [comment]
Tested this with the code from the main branch
```
GEOS Version 3.13.0dev-CAPI-1.18.0
Geometry: LINESTRING Z EMPTY
GEOSHasZ() = 1
```

I would expect this code to create a 2D geometry.

**Comment by pramsey** [comment]
I'm not able to replicate this on main or on 3.12 branch.

**Comment by pramsey** [comment]
The culprit is pretty deep inside GEOS. Once upon a time, GEOS only had three dimensions and every Coordinate had an x/y/z member.  Then in the last release, the CoordinateSequence was generalized to live on a double[] buffer instead, which allowed for XY, XYM, XYZ XYZM variants. But most of the code still expected Coordinate. So a lot of assumptions about default size remained in place.

The culprit for this particular case is in

https://github.com/libgeos/geos/blob/4767afd144f86a7a2be0f796639eac34ea5760eb/src/geom/CoordinateSequence.cpp#L72

where the stride is initialized to '3'. Also in the constructor above you can see similar logic around what the default stride should be. The stride then leaks out in places like CoordinateSequence::getDimension. @mwtoews perhaps can see if this is fixable without surgery.

**Comment by dbaston** [comment]
I'm not sure if the behavior of `GEOSGeom_createLineString(NULL)` is defined anywhere. `GEOSGeom_createEmptyLineString()` will produce an empty 2d linestring.

**Comment by pramsey** [comment]
Sounds like a documentation issue.

**Comment by dr-jts** [comment]
> I'm not sure if the behavior of `GEOSGeom_createLineString(NULL)` is defined anywhere. `GEOSGeom_createEmptyLineString()` will produce an empty 2d linestring.

To me it makes sense that `GEOSGeom_createLineString(NULL)` should have the same behaviour as `GEOSGeom_createEmptyLineString()`.
